name: "✨ Feature Request"
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the details below.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of your idea
      placeholder: "Add a .removePunctuation() transformation"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful?
      placeholder: "Regex for removing punctuation is tricky, this helper would simplify it"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other solutions or workarounds?
      placeholder: "I could write my own regex, but readability suffers"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other details, screenshots, or references here.
